export function ecoExplorer(T) {
  return `<section class="eco-explorer" aria-label="${T('เลือกเส้นทางของคุณ','Choose your next step')}">
    <div class="eco-explorer-intro"><span class="kicker">EXPLORE GOODKIND</span><h2>${T('เลือกสิ่งดี ๆ ที่เหมาะกับคุณ','Find your kind of good.')}</h2></div>
    <article><span class="eco-audience">FOR YOUR EVERYDAY</span><h3>${T('สินค้าและประสบการณ์ใกล้คุณ','Products & places for you')}</h3><p>${T('ค้นพบสินค้าเพื่อสุขภาวะ ดูบริการและเวลาเปิดสาขา แล้วเลือกเส้นทางไปพบเรา','Discover wellness essentials, explore local services and opening hours, then plan your visit.')}</p><div><a class="eco-submit" href="#/eco/stores">${T('ค้นหาสาขาใกล้คุณ','Find a location')} →</a><a class="outline-link" href="#/eco/portfolio">${T('ดูสินค้าและบริการ','Explore our portfolio')}</a></div></article>
    <article><span class="eco-audience">FOR YOUR BUSINESS</span><h3>${T('เติบโตไปด้วยกัน','Let’s grow together')}</h3><p>${T('เสนอแบรนด์หรือสินค้าของคุณ สำรวจโอกาสจัดจำหน่าย หรือพูดคุยเรื่องโครงการสุขภาวะองค์กร','Introduce your brand or products, explore distribution opportunities or plan a corporate wellness project.')}</p><div><a class="eco-submit" href="#/eco/partners?interest=supplier">${T('เสนอสินค้า / ร่วมธุรกิจ','Introduce your business')} →</a></div></article>
  </section>`
}

export function ecoHighlights(T, photos) {
  const items = [
    {brand:'NOURISH LAB',name:T('Daily Essentials · กิจวัตรที่ใส่ใจ','Daily Essentials'),desc:T('ผลิตภัณฑ์สำหรับกิจวัตรดูแลตัวเอง พร้อมคำแนะนำที่สาขา','Everyday wellness essentials with guidance in store.'),photo:photos.product1},
    {brand:'GOODKIND BOTANICS',name:T('Botanical Body Care · ดูแลผิวทุกวัน','Botanical Body Care'),desc:T('บอดี้แคร์สำหรับช่วงเวลาพักและการดูแลผิวประจำวัน','Thoughtful body care for your daily rituals.'),photo:photos.product2},
    {brand:'SLOW SUNDAY',name:T('Rest & Reset · ช่วงเวลาของคุณ','Rest & Reset'),desc:T('ของใช้สำหรับมุมพักผ่อนที่เข้ากับจังหวะชีวิตของคุณ','Considered essentials for a quieter moment at home.'),photo:photos.product3},
  ]
  return `<section class="eco-highlights"><div class="section-lead"><div><span class="kicker">DISCOVER IN STORE</span><h2>${T('สินค้าไฮไลต์สำหรับทุกวัน','Good finds for everyday life')}</h2><p>${T('ทำความรู้จักแบรนด์คัดสรร แล้วค้นหาสาขาเพื่อสอบถามสินค้าและบริการ','Meet our curated brands, then find a location to ask about products and services.')}</p></div><a class="outline-link" href="#/eco/portfolio">${T('ดูสินค้าและบริการทั้งหมด','Explore the portfolio')} →</a></div><div class="eco-highlight-grid">${items.map(item=>`<article><img src="${item.photo}" alt="${item.name}" loading="lazy"><div><span class="kicker">${item.brand}</span><h3>${item.name}</h3><p>${item.desc}</p><a href="#/eco/stores">${T('ค้นหาสาขาเพื่อสอบถามสินค้า','Find a location to enquire')} →</a></div></article>`).join('')}</div><p class="prototype-note">${T('สินค้าและแบรนด์เป็นตัวอย่างสำหรับเดโม การมีสินค้าในแต่ละสาขาต้องยืนยันกับสาขา','Illustrative products and brands for this demo. Check availability with the location.')}</p></section>`
}

export function ecoNewsletter(T) {
  return `<section class="eco-journal-follow"><div><span class="kicker">THE GOODKIND LETTER</span><h2>${T('ให้เรื่องดี ๆ อยู่ในทุกวัน','A little good, in your inbox.')}</h2><p>${T('ติดตามบทความวิถีชีวิตสุขภาพ เรื่องราวชุมชน และกิจกรรมครั้งต่อไปจาก Goodkind','Follow everyday wellness ideas, community stories and upcoming Goodkind events.')}</p><a class="outline-link" href="#/eco/journal">${T('อ่าน Wellness Journal','Read the Wellness Journal')} →</a></div><form data-form="eco-newsletter"><label for="eco-newsletter-email">${T('อีเมลของคุณ','Your email')}</label><div class="eco-subscribe-row"><input id="eco-newsletter-email" name="email" type="email" autocomplete="email" required placeholder="you@example.com"><button class="eco-submit">${T('ติดตามข่าวสาร','Subscribe')} →</button></div><label class="consent"><input type="checkbox" name="consent" required> ${T('ยินยอมรับบทความและข่าวสารจาก Goodkind','I agree to receive Goodkind stories and updates.')}</label><p class="prototype-note">${T('แบบฟอร์มตัวอย่าง · ยังไม่มีการบันทึกข้อมูลหรือส่งอีเมลจริง','Demo form · no data is stored and no email is sent.')}</p><p class="form-message" role="status"></p></form></section>`
}

export function initEcoJourney(r,T) {
  if(r.brand!=='eco')return
  const meta={home:[T('Goodkind · สินค้า บริการ และสุขภาวะใกล้คุณ','Goodkind · Everyday Wellness, Products & Places'),T('ค้นพบสินค้าและบริการสุขภาวะ ค้นหาสาขาใกล้คุณ สำรวจโอกาสร่วมธุรกิจ และอ่าน Wellness Journal','Discover wellness products and services, find a location, explore partnerships and read the Wellness Journal.')],story:[T('เรื่องราวและค่านิยม | Goodkind','Our Story & Values | Goodkind'),T('รู้จักแนวคิดของ Goodkind ที่เชื่อมสินค้า บริการ พันธมิตร และชุมชนสุขภาวะ','Explore the Goodkind vision connecting products, services, partners and communities.')],portfolio:[T('สินค้าและบริการ | Goodkind','Products & Services | Goodkind'),T('สำรวจแบรนด์คัดสรร สินค้าไฮไลต์ และบริการเพื่อสุขภาวะของ Goodkind','Explore curated brands, featured products and Goodkind wellness services.')],stores:[T('ค้นหาสาขาและเส้นทาง | Goodkind','Locations & Directions | Goodkind'),T('ค้นหาสาขาตามพื้นที่ ดูเวลาเปิด บริการ แผนที่ และเส้นทาง สำหรับข้อมูลสาขาตัวอย่าง','Search illustrative Goodkind locations, opening hours, services and directions.')],partners:[T('เสนอสินค้าและร่วมธุรกิจ | Goodkind','Business Partnerships & Supplier Enquiries | Goodkind'),T('สำรวจโอกาสเสนอสินค้า จัดจำหน่าย แฟรนไชส์ และโครงการสุขภาวะองค์กร พร้อมแบบฟอร์มสอบถามตัวอย่าง','Explore supplier, retail, wholesale and corporate wellness partnerships with a demo enquiry form.')],journal:[T('Wellness Journal และชุมชน | Goodkind','Wellness Journal & Community | Goodkind'),T('อ่านบทความวิถีชีวิตสุขภาพ เรื่องราวชุมชน และติดตามกิจกรรม Goodkind','Read everyday wellness ideas, community stories and upcoming Goodkind events.')],events:[T('กิจกรรมและเวิร์กช็อป | Goodkind','Events & Workshops | Goodkind'),T('สำรวจกิจกรรมและเวิร์กช็อปชุมชน Goodkind พร้อมแบบฟอร์มลงทะเบียนตัวอย่าง','Explore Goodkind community activities and workshops with demo registration.')],contact:[T('ติดต่อเรา | Goodkind','Contact Us | Goodkind'),T('ติดต่อ Goodkind เพื่อสอบถามบริการ สาขา และโอกาสร่วมธุรกิจ','Contact Goodkind about services, locations and business opportunities.')]}
  const current=meta[r.page]||meta.home
  document.title=current[0]
  document.querySelector('meta[name="description"]').content=current[1]
  const interest=document.querySelector('form[data-form="partner"] select[name="interest"]')
  if(interest&&['supplier','retail','wholesale','franchise','corporate'].includes(r.params.get('interest')))interest.value=r.params.get('interest')
}
